name: Metrics 3D

on:
  schedule: [{cron: "0 1 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics-3d:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: vaishnavijha12
          filename: metrics-3d.svg

          base: header

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_isocalendar_mode: 3d

          config_theme: dark
